### ISSUE TITLE
User Defined fields for Reporting

### ISSUE THREAD

**Issue by papyr** [EasyAbp/Abp.DynamicEntity#2]
Please consider user defined Fields UDF for reporting and attaching to charts/widgets as data sources.

**Comment by wakuflair** [comment]
There's no plan for adding UI specified fields for now.

**Comment by papyr** [comment]
Ok please consider, because sometimes users want two or three more fields for their custom business.

https://stackoverflow.com/q/5106335/6085193
https://stackoverflow.com/a/961234/6085193
https://support.aspnetzero.com/QA/Questions/4539/Custom-Fields
https://martinfowler.com/bliki/UserDefinedField.html
