### ISSUE TITLE
Uncaught TypeError: $(...).sortable is not a function

### ISSUE THREAD

**Issue by ayeah** [EasyAbp/Abp.DynamicEntity#5]
[Remove datatables-extensions.js, jquery-ui.min.js and jquery-ui.min.css](https://github.com/EasyAbp/Abp.DynamicEntity/commit/3763932c438e6d5cc01178dd887a150cffd3d864)[](https://github.com/gdlcf88)

@[gdlcf88](https://github.com/EasyAbp/Abp.DynamicEntity/commits?author=gdlcf88)
gdlcf88 committed on 1 Jan 2022

I've found the cause of this error, the lack of jquery-ui will make front-end page not working. Also  reproduceable in your sample site.

**Comment by gdlcf88** [comment]
https://github.com/abpframework/abp/commit/ecbc2bcc845d3557739ed3933ffc8247f95bca5d

The sort bar is only a sample. I removed these files since they are outdated. You can try to fix the problem and create a PR.

**Comment by Tranphat-freelancer** [comment]
My UI skills are not good, but I quite need this feature can you give me some advice to fix it? @gdlcf88 
（；´д｀）ゞ

**Comment by gdlcf88** [comment]
> My UI skills are not good, but I quite need this feature can you give me some advice to fix it? @gdlcf88 （；´д｀）ゞ

I will do it when I have time. If you want to contribute, try to compare it with other modules.

**Comment by ayeah** [comment]
> My UI skills are not good, but I quite need this feature can you give me some advice to fix it? @gdlcf88 （；´д｀）ゞ

simply use the link in this post, add jquery-ui back to this file 
`[src/EasyAbp.Abp.DynamicEntity.Web/Pages/DynamicEntity/ModelDefinition/Index.cshtml]`

you can create a file with same name and same path in your `Web` project to override the file in the package

**Comment by gdlcf88** [comment]
@Tranphat-freelancer Please try again.

**Comment by ayeah** [comment]
### Good job! 

Thumbs up!
